"""Canonical knowledge-store schemas."""

from app.schemas.claims import ClaimExtractionStatus, EvidenceStatus, ExtractedClaim
from app.schemas.entities import EntityType, ExternalId, KnowledgeEntity
from app.schemas.ground_truth import (
    CandidateKind,
    CandidateStatus,
    DiscoveryPath,
    ExternalPaperId,
    GroundTruthArtifact,
    GroundTruthJob,
    GroundTruthStage,
    GroundTruthStageName,
    PaperAcquisition,
    PaperAuthor,
    PaperCandidate,
    PaperChunk,
    PaperMetadata,
    PaperProcessingStatus,
    PaperSummary,
    SourceDecision,
    SourceProvider,
)
from app.schemas.ingestion import (
    ArtifactStatus,
    ArtifactType,
    IngestionJob,
    IngestionStage,
    IngestionStageName,
    JobLifecycleStatus,
    ResearchBasisCandidate,
    ResearchBasisStatus,
    ResearchBasisTriage,
    ScreenshotArtifact,
    SourceKind,
    StageStatus,
    TranscriptArtifact,
    TranscriptProvenance,
    TranscriptRetrievalMethod,
    TranscriptSegment,
)
from app.schemas.relationships import KnowledgeRelationship, RelationshipType

__all__ = [
    "ArtifactStatus",
    "ArtifactType",
    "ClaimExtractionStatus",
    "CandidateKind",
    "CandidateStatus",
    "DiscoveryPath",
    "EntityType",
    "EvidenceStatus",
    "ExternalId",
    "ExternalPaperId",
    "ExtractedClaim",
    "GroundTruthArtifact",
    "GroundTruthJob",
    "GroundTruthStage",
    "GroundTruthStageName",
    "IngestionJob",
    "IngestionStage",
    "IngestionStageName",
    "JobLifecycleStatus",
    "KnowledgeEntity",
    "KnowledgeRelationship",
    "PaperAcquisition",
    "PaperAuthor",
    "PaperCandidate",
    "PaperChunk",
    "PaperMetadata",
    "PaperProcessingStatus",
    "PaperSummary",
    "RelationshipType",
    "ResearchBasisCandidate",
    "ResearchBasisStatus",
    "ResearchBasisTriage",
    "ScreenshotArtifact",
    "SourceDecision",
    "SourceKind",
    "SourceProvider",
    "StageStatus",
    "TranscriptArtifact",
    "TranscriptProvenance",
    "TranscriptRetrievalMethod",
    "TranscriptSegment",
]
